- name: US
  password: <解锁项目的uuid>
  address: node-us.nfdns.xyz
  outbound_port: 38383
  streaming_service: Netflix, YouTube, Disney+, TikTok, Bilibili, VIU, TVB, PrimeVideo, DAZN, ChatGPT, Discovery+, ESPN+, Fox, FuboTV, HBO Max, Paramount+, PeacokTV, Star+, BritBox, FXNOW, Philo, Shudder, TLCGO

- name: JP
  password: <解锁项目的uuid>
  address: node-jp.nfdns.xyz
  outbound_port: 38123
  streaming_service: Netflix, YouTube, Disney+, TikTok, Bilibili, VIU, TVB, PrimeVideo, DAZN, ChatGPT, Spotify, Abema, DAM, DMM, FOD, Music_JP, Niconico, Radiko, Telasa, UNEXT

- name: HK
  password: <解锁项目的uuid>
  address: node-hk.nfdns.xyz
  outbound_port: 38888
  streaming_service: Netflix, YouTube, Disney+, TikTok, Bilibili, VIU, TVB, PrimeVideo, DAZN, ChatGPT, Spotify, HboGO, KKTV, LiTV, LineTV, MyTvSuper, NowE, Bahamut, CatchPlay

- name: TW
  password: <解锁项目的uuid>
  address: node-tw.nfdns.xyz
  outbound_port: 20558
  streaming_service: Netflix, YouTube, Disney+, TikTok, Bilibili, VIU, TVB, PrimeVideo, DAZN, ChatGPT, Spotify, HboGO, KKTV, LiTV, LineTV, MyTvSuper, NowE, Bahamut, CatchPlay

- name: SG
  password: <解锁项目的uuid>
  address: node-sg.nfdns.xyz
  outbound_port: 20955
  streaming_service: Netflix, YouTube, Disney+, TikTok, Bilibili, VIU, TVB, PrimeVideo, DAZN, ChatGPT, Spotify, HboGO, KKTV, LiTV, LineTV, MyTvSuper, NowE, Bahamut, CatchPlay

- name: KR
  password: <解锁项目的uuid>
  address: node-kr.nfdns.xyz
  outbound_port: 23355
  streaming_service: Netflix, YouTube, Disney+, TikTok, Bilibili, VIU, TVB, PrimeVideo, DAZN, ChatGPT, Spotify, Wavve, Tving, CoupangPlay, NaverTV, AfreecaTV, KBSDomestic, Watcha, SpotvNow

- name: EU
  password: <解锁项目的uuid>
  address: node-uk.nfdns.xyz
  outbound_port: 25253
  streaming_service: Netflix, YouTube, Disney+, TikTok, Bilibili, VIU, TVB, PrimeVideo, DAZN, ChatGPT, Spotify, BBC

